### ISSUE TITLE
THTMLTags

### ISSUE THREAD

**Issue by ericksonl** [nay7/Elemental#6]
Index.html is missing a closed tag for < h1 >. This needs to be added below the element list link, as the element list also needs to be formatted in h1.

**Comment by nay7** [comment]
A closed html tag has been added to the index.html file. Both headers should now be formatted in h1.

**Comment by oppenheip** [comment]
This was not a bug in the original source. It worked fine as is. Also, this isn't a bug that a tester would find. Assume your tester is just a user and doesn't know HTML.
